FROM node:16.15.0-alpine

# Working directory
WORKDIR /client

RUN apk update && apk add --no-cache nodejs npm python3 py3-pip build-base

COPY ./package.json ./package-lock.json ./
RUN npm install --slient

COPY . .
