FROM node:16.15.0-alpine

# Working directory
WORKDIR /frontend

ENV PATH /frontend/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm instal --slient

COPY . ./

CMD ["npm", "start"]
