FROM golang:1.17-alpine

# Working directory
WORKDIR /api

COPY . .

RUN apk update && apk add --no-cache git

# Go envs
ENV GOOS=linux CGO_ENABLED=0

RUN go mod download && go mod verify

# Live reload for Go
RUN go install github.com/cosmtrek/air@latest

EXPOSE 9000
